config/routes.rb
Rails.application.routes.draw do
 
 
 resources :news
 resources :pressreleases
 

  resources :endorsements
  resources :users
    get '/signup' => 'users#new'
    post '/users' => 'users#create'
    get 'users', to: 'users#index'
    
    
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
    

 get 'contact/new'
 resources :contact, only: [:new, :create]
 get '/contact', to: 'contact#new'
 
 match '/send_mail', to: 'contact#send_mail', via: 'post'
 
 get 'admin/' => 'admin#index'
 
  get 'donate/' => 'donate#index'

  get 'support/' => 'support#index'
  
   get 'edit_organizations' => 'endorsements#edit_organizations'

  get 'endorsements' => 'endorsements#index'
  
 

  get 'faq/' => 'faq#index'

  get 'about/' => 'about#index'

  get 'welcome/index'

  root 'welcome#index'

end

app/models/contact.rb
class Contact 
  
  include ActiveModel::Model

  attr_accessor :firstname, :lastname, :email, :message, :type, :endorser, :mailingaddress, :city, :state, :zip, :phone, :language

  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :email, presence: true
 
end

app/models/endorsement.rb
class Endorsement < ActiveRecord::Base
 
 
 
default_scope  {order 'ranking ASC', 'lastname ASC', 'organization ASC'}
   
   validates :category, presence: true
end

app/models/news.rb
class News < ActiveRecord::Base
 extend FriendlyId
   friendly_id :title, use: :slugged
   
 has_attached_file :avatar, styles: { medium: "585x380#>", thumb: "120x80>" }, default_url: "/images/missing.png"


 validates_attachment :avatar,
   content_type: { content_type: ["image/jpg", "image/JPEG", "image/JPG", "image/jpeg", "image/gif", "image/png"] }
   
    default_scope  {order 'published_at DESC'}
    
end

app/models/pressrelease.rb
class Pressrelease < ActiveRecord::Base
 extend FriendlyId
   friendly_id :title, use: :slugged
   
  validates :title, presence: true
  validates :intro, presence: true
  validates :body, presence: true
  
   default_scope  {order 'publish_at DESC'}
   
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
   @title = "About Prop 58"
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
 
 before_filter :authorize 
 
  def index
   @title = "Admin Center"
  end
end

app/controllers/faq_controller.rb
class FaqController < ApplicationController

  def index
   @title = "Frequently Asked Questions"
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]
before_filter :authorize, except: [:index, :show]
  # GET /news
  # GET /news.json
  def index
    @news = News.all
    @title = "News"
  end

  # GET /news/1
  # GET /news/1.json
  def show
   @ns = News.all
  
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)
    
    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url, notice: 'News was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:title, :intro, :body, :published_at, :avatar)
    end
end

app/controllers/pressreleases_controller.rb
class PressreleasesController < ApplicationController
  before_action :set_pressrelease, only: [:show, :edit, :update, :destroy]
  before_filter :authorize, except: [:index, :show]
  # GET /pressreleases
  # GET /pressreleases.json
  def index
    @pressreleases = Pressrelease.all
    @title = "Press Releases"
  end

  # GET /pressreleases/1
  # GET /pressreleases/1.json
  def show
   @prs = Pressrelease.all
  end

  # GET /pressreleases/new
  def new
    @pressrelease = Pressrelease.new
  end

  # GET /pressreleases/1/edit
  def edit
  end

  # POST /pressreleases
  # POST /pressreleases.json
  def create
    @pressrelease = Pressrelease.new(pressrelease_params)

    respond_to do |format|
      if @pressrelease.save
        format.html { redirect_to @pressrelease, notice: 'Pressrelease was successfully created.' }
        format.json { render :show, status: :created, location: @pressrelease }
      else
        format.html { render :new }
        format.json { render json: @pressrelease.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pressreleases/1
  # PATCH/PUT /pressreleases/1.json
  def update
    respond_to do |format|
      if @pressrelease.update(pressrelease_params)
        format.html { redirect_to @pressrelease, notice: 'Pressrelease was successfully updated.' }
        format.json { render :show, status: :ok, location: @pressrelease }
      else
        format.html { render :edit }
        format.json { render json: @pressrelease.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pressreleases/1
  # DELETE /pressreleases/1.json
  def destroy
    @pressrelease.destroy
    respond_to do |format|
      format.html { redirect_to pressreleases_url, notice: 'Pressrelease was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pressrelease
      @pressrelease = Pressrelease.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pressrelease_params
      params.require(:pressrelease).permit(:title, :publish_at, :intro, :body)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :set_user, only: [:show, :edit, :update, :destroy]
before_filter :authorize


 def index
  @users = User.all
 end
 
 
  def new
  end

  def create
    user = User.new(user_params)
    if user.save
      
      redirect_to users_path, notice: 'User has been added!'
    else
      redirect_to '/signup'
    end
  end
  
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private
 # Use callbacks to share common setup or constraints between actions.
 def set_user
   @user = User.find(params[:id])
 end
 
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/donate_helper.rb
module DonateHelper
end

app/helpers/endorsements_helper.rb
module EndorsementsHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/pressreleases_helper.rb
module PressreleasesHelper
end

app/helpers/support_helper.rb
module SupportHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/pressreleases/_form.html.erb
<%= bootstrap_form_for(@pressrelease) do |f| %>
 

	 <fieldset class="form-group">
		
		 <div class="field">
    <%= f.text_field :title %>
  </div>
  <div class="field ">
    <%= f.datetime_select :publish_at %>
  </div>
  <div class="field">
    <%= f.text_area :intro, class: "edit-intro" %>
  </div>
   <div class="field">
    <%= f.text_area :body , id: "summernote"%>
  </div>
  <div class="actions pull-right">
    <%= f.submit %>
  </div>
<% end %>

</fieldset>

<script type="text/javascript">
$('#summernote').summernote({
	 shortcuts: false,
	dialogsInBody: false,
	popover:false,
  toolbar: [
    // [groupName, [list of button]]
			 ['para', ['style', 'ul']],
	  ['insert', ['link']],
	  ['image', ['none']],
    ['style', ['bold', 'italic', 'underline', 'clear']]	
   
  ],
		styleTags: ['p', 'h4']
});
</script>

app/views/pressreleases/edit.html.erb
<% content_for :admin do %>
<div class="container">
	<div class="row">

<div class="admin-panel ">
	<h1>Edit Press Release</h1>
	
	
<%= render 'form' %>


<p class="bta"><i class="fa fa-arrow-left" aria-hidden="true"></i> <%= link_to 'Back to Admin', admin_path %>
</div>

</div>
</div>
<% end %>

app/views/pressreleases/index.html.erb
<%= content_for :full do %>
       
													<div class="col-md-8 full">
														
								 <h1>Press Releases</h1>
				
				<p>For more information, please contact Communications Director:
					 <br/><strong>Robin Swanson</strong>, tel: (916) 204-6890</p>
				
				<% @pressreleases.each do |pr| %>
				
				<div class="prs">
				<h2><%= link_to pr.title, pr %></h2>
				<h6 class="text-muted"><%= pr.publish_at.strftime("%B %d %Y")%></h6> 
				 <p class="intro-p"><%= pr.intro %> <span class="read-more"><%= link_to 'Read more', pr %> <i class="fa fa-arrow-right" aria-hidden="true"></i></span></p>
					
				</div>
				<% end %>										

</div>








<div class="col-md-4 rh">
	
	<% if current_user %><div class="edit alert" >
	 <%= link_to ' Add a new PR', new_pressrelease_path, class: "admin-edit fa fa-plus", dismissible: true %>

	 <button class="close" data-dismiss="alert" type="button">
	     <span aria-hidden="true">×</span><span class="sr-only">Close</span>
	   </button>

	 </div>
	 <% end %>
</div>


<% end %>

app/views/pressreleases/new.html.erb
<% content_for :admin do %>
<div class="container">
	<div class="row">

<div class="admin-panel ">
	<h1>Add Press Release</h1>
	
	
<%= render 'form' %>


<p class="bta"><i class="fa fa-arrow-left" aria-hidden="true"></i> <%= link_to 'Back to Admin', admin_path %>
</div>

</div>
</div>

<% end %>

app/views/pressreleases/show.html.erb
<%= content_for :head do %>
<script type='text/javascript' data-cfasync='false' src='//dsms0mj1bbhn4.cloudfront.net/assets/pub/shareaholic.js' data-shr-siteid='2a3a338d5a793821ef975b0f0e3b37ae' async='async'></script>

<% @title = @pressrelease.title %>
<% end %>


<%= content_for :full do %>

<div class="col-md-8 full">

	 	<% if current_user %>
	 	<div class="edit alert" >
	 <i> <%= link_to ' Edit ', edit_pressrelease_path(@pressrelease), class: "admin-edit fa fa-edit", dismissible: true %> </i>|<i> <%= link_to ' Delete', @pressrelease, method: :delete, data: { confirm: 'Are you sure?' }, class: "admin-edit fa fa-trash" %></i>
 
	 <button class="close" data-dismiss="alert" type="button">
	     <span aria-hidden="true">×</span><span class="sr-only">Close</span>
	   </button>
   
	 </div>
	<% end %>
	
  <h2>
  <%= @pressrelease.title %>
</h2>

<div class="date-share-row">
<div class="col-sm-4 date-col">
<h6 class="text-muted"><%= @pressrelease.publish_at.to_time.strftime('%B %d %Y')%></h6> 
</div>
<div class="col-sm-8 share-col">
	<div class='shareaholic-canvas share-icons' data-app='share_buttons' data-app-id='25528828'></div>
</div>
</div>
	
<p class="lead">
 
  <%= @pressrelease.intro %>
</p>


<div class="pr-body"><%= simple_format(@pressrelease.body) %></div>

<p class="bta"><i class="fa fa-arrow-left" aria-hidden="true"></i> <%= link_to 'Back to Press Releases', pressreleases_path %>
	
</div>

<div class="rh col-md-4">
	 	
	
	<% @prs.each do |pr| %>
	<% unless pr == @pressrelease %>
	<h4><%= link_to pr.title, pr %></h4>
	<h6 class="text-muted"><%= pr.publish_at.strftime("%B %d %Y")%></h6> 
	<% end %>
	<% end %>
	
	
</div>
<% end %>