config/routes.rb
Rails.application.routes.draw do
 
 
 resources :news
 resources :pressreleases
 

  resources :endorsements
  resources :users
    get '/signup' => 'users#new'
    post '/users' => 'users#create'
    get 'users', to: 'users#index'
    
    
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
    

 get 'contact/new'
 resources :contact, only: [:new, :create]
 get '/contact', to: 'contact#new'
 
 match '/send_mail', to: 'contact#send_mail', via: 'post'
 
 get 'admin/' => 'admin#index'
 
  get 'donate/' => 'donate#index'

  get 'support/' => 'support#index'
  
   get 'edit_organizations' => 'endorsements#edit_organizations'

  get 'endorsements' => 'endorsements#index'
  
 

  get 'faq/' => 'faq#index'

  get 'about/' => 'about#index'

  get 'welcome/index'

  root 'welcome#index'

end

app/models/contact.rb
class Contact 
  
  include ActiveModel::Model

  attr_accessor :firstname, :lastname, :email, :message, :type, :endorser, :mailingaddress, :city, :state, :zip, :phone, :language

  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :email, presence: true
 
end

app/models/endorsement.rb
class Endorsement < ActiveRecord::Base
 
 
 
default_scope  {order 'ranking ASC', 'lastname ASC', 'organization ASC'}
   
   validates :category, presence: true
end

app/models/news.rb
class News < ActiveRecord::Base
 extend FriendlyId
   friendly_id :title, use: :slugged
   
 has_attached_file :avatar, styles: { medium: "585x380#>", thumb: "120x80>" }, default_url: "/images/missing.png"


 validates_attachment :avatar,
   content_type: { content_type: ["image/jpg", "image/JPEG", "image/JPG", "image/jpeg", "image/gif", "image/png"] }
   
    default_scope  {order 'published_at DESC'}
    
end

app/models/pressrelease.rb
class Pressrelease < ActiveRecord::Base
 extend FriendlyId
   friendly_id :title, use: :slugged
   
  validates :title, presence: true
  validates :intro, presence: true
  validates :body, presence: true
  
   default_scope  {order 'publish_at DESC'}
   
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
   @title = "About Prop 58"
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
 
 before_filter :authorize 
 
  def index
   @title = "Admin Center"
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
 def new
  
     @contact = Contact.new
     @support = ['Distribute Materials', 'Write an opinion editorial', 'Communicate with employees/members','Volunteer/Speak at local events', 'Write a letter-to-the editor', 'Our organization offers speakers in the following languages (use comment box)']
     @title = "Contact us"
   end
   
   
   def create
      
     @contact = Contact.new(params[:contact])
     firstname = @contact.firstname
     lastname = @contact.lastname
     email = @contact.email
     message = @contact.message
     type = @contact.type
     endorser = @contact.endorser
     mailingaddress = @contact.mailingaddress
     city = @contact.city
     state = @contact.state
     zip = @contact.zip
     phone = @contact.phone
     language = @contact.language
     
     
    
     @support = params[:support]
     
     if @contact.valid?
       ContactMailer.contact_email(firstname, lastname, email, message, type, endorser, mailingaddress, city, state, zip, phone, language, @support).deliver_now
       redirect_to root_path, notice: 'Thank you - your message has been sent!'
     else
         @support = ['Distribute Materials', 'Write an opinion editorial', 'Communicate with employees/members','Volunteer/Speak at local events', 'Write a letter-to-the editor', 'Our organization offers speakers in the following languages (use comment box)']
       render :new
     end
   end
   
   
   
end

app/controllers/donate_controller.rb
class DonateController < ApplicationController
  def index
   @title = "Contribute to Prop 58"
  end
end

app/controllers/faq_controller.rb
class FaqController < ApplicationController

  def index
   @title = "Frequently Asked Questions"
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]
before_filter :authorize, except: [:index, :show]
  # GET /news
  # GET /news.json
  def index
    @news = News.all
    @title = "News"
  end

  # GET /news/1
  # GET /news/1.json
  def show
   @ns = News.all
  
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)
    
    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url, notice: 'News was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:title, :intro, :body, :published_at, :avatar)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :set_user, only: [:show, :edit, :update, :destroy]
before_filter :authorize


 def index
  @users = User.all
 end
 
 
  def new
  end

  def create
    user = User.new(user_params)
    if user.save
      
      redirect_to users_path, notice: 'User has been added!'
    else
      redirect_to '/signup'
    end
  end
  
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private
 # Use callbacks to share common setup or constraints between actions.
 def set_user
   @user = User.find(params[:id])
 end
 
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/donate_helper.rb
module DonateHelper
end

app/helpers/endorsements_helper.rb
module EndorsementsHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/pressreleases_helper.rb
module PressreleasesHelper
end

app/helpers/support_helper.rb
module SupportHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contact/new.html.erb
<%= content_for :jumbotron do %>
<div class="contact-jumbotron">
    <!-- Intro Section -->
    <section id="intro" class="intro-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                   
					
                    
                </div>
            </div>
        </div>
    </section>
</div>

<% end %>
<div class="sub-intro-section">
        <div class="container">
            <div class="row contact-form">
													<div class="col-md-6 offset-md-3">
                    <h2>Contact us</h2>
																				
		<%= bootstrap_form_for @contact, url: {:action=>'create'} do |f| %>	

<%= f.text_field :firstname %>
<%= f.text_field :lastname %>
<%= f.email_field :email %>

<%= f.text_area :message %>

<h4>Add me as an Endorser</h4>
<div class="clearfix"></div>

<%= f.select :type,  [["Organization"], ["Company"], ["Individual"], ["Elected Official"]],{ include_blank: true , label: "Please choose one:" }, { class: "selectpicker" } %>

<%= f.text_field :endorser, placeholder:"Name, title, you would like to be listed as", label:"Title / Organization" %>

<%= f.text_field :mailingaddress, placeholder:"Street", label:"Mailing address" %>
<%= f.text_field :city, placeholder:"City" %>
<%= f.text_field :state, placeholder:"State" %>
<%= f.text_field :zip, placeholder:"Zip" %>
<%= f.text_field :phone, placeholder:"Phone" %>



																																																																																																																																																																																																																																																																									

<h4>Support Proposition 58</h4>
<div class="clearfix"></div>


<%= f.form_group :help do %><br/>

<% @support.each do |item| %>
<div class="checkbox" style="margin-left:20px"><%= check_box_tag "support[]", item %> <%= item %></div>

<% end %>
<% end %>
<%= f.text_field :language, placeholder:"language(s)", hide_label: true  %>
						
				

 <%= f.submit "Send", class: "btn btn-default btn-about pull-right" %>


					
				  </div>
                </div>
            </div>
        </div>
    </section>
			
			
			
																			      <section class="b-section">
																			          <div class="container">
																			              <div class="row">
																			                  <div class="col-md-10 offset-md-1">
																			                      <h2>Our contact details</h2>
																				
		<p><strong>Yes on 58 - Californians for English Proficiency</strong><br/>
																																									  1510 J Street, Suite 210<br/>
		Sacramento, CA 95814</p>
																																																																																																																				
																																																																																																																					<p><strong>Tel:</strong>  (916) 668-9103</p>


					
				
																			                  </div>
																			              </div>
																			          </div>
																			      </section>
																								
		
				<% end %>
	

app/views/news/_form.html.erb
<%= bootstrap_form_for(@news, :html => { :multipart => true }) do |f| %>
  
	 <fieldset class="form-group">
  <div class="field">

    <%= f.text_field :title %>
  </div>
  <div class="field">
			
	  <div class="field">
   
	    <%= f.text_field :published_at, label:"When do you want the story to appear as published?", :id => "datepicker" %>
	  </div>
			
 	  <% unless @news.avatar.blank? %>
 	  <p><b>Current image</b><br/><%= link_to (image_tag @news.avatar.url(:thumb)), @news.avatar.url(:original), target: '_blank' %> </p><%= f.file_field :avatar, label: 'Add a new image', class: 'choose-image'%></p>
 	  <% else %>
 	  <div class="field">
 	  <%= f.file_field :avatar, label: 'Add an image for this story - ', class: 'choose-image'%>
   </div>
 	  <% end %>

    <%= f.text_area :intro %>
  </div>
  <div class="field">
   
     <%= f.text_area :body , id: "summernote"%>
  </div>
 
 <div class="actions pull-right">
   <%= f.submit %>
 </div>
<% end %>

<script type="text/javascript">
$('#summernote').summernote({
	 shortcuts: false,
	dialogsInBody: false,
	popover:false,
  toolbar: [
    // [groupName, [list of button]]
			 ['para', ['style', 'ul']],
	  ['insert', ['link']],
	  ['image', ['none']],
    ['style', ['bold', 'italic', 'underline', 'clear']]	
   
  ],
		styleTags: ['p', 'h4']
});
</script>

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.0/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js"></script>

<script>
$( function() {
	$( "#datepicker" ).datepicker({
	  dateFormat: "yy-mm-dd"
	});
} );


</script>

app/views/news/edit.html.erb
<% content_for :admin do %>
<div class="container">
	<div class="row">

<div class="admin-panel ">
	<h1>Edit this News Story</h1>

<%= render 'form' %>

<p class="bta"><i class="fa fa-arrow-left" aria-hidden="true"></i> <%= link_to 'Back to News', news_index_path %>
</div>

</div>
</div>

<% end %>

app/views/news/index.html.erb
<%= content_for :full do %>
       
													<div class="col-md-8 full">
														
								 <h1>In the News</h1>
				
		
				
				<% @news.each do |n| %>
				
			
				<div class="prs">
				<h2><%= link_to n.title, n %></h2>
				<h6 class="text-muted"><%= n.published_at.to_time.strftime('%B %d %Y')%></h6>
				 <p class="intro-p"><%= n.intro %> <span class="read-more"><%= link_to 'Read more', n %> <i class="fa fa-arrow-right" aria-hidden="true"></i></span></p>
					
				</div>
				<% end %>										

</div>








<div class="col-md-4 rh">
	
	<% if current_user %><div class="edit alert" >
	 <%= link_to ' Add a new Story', new_news_path, class: "admin-edit fa fa-plus", dismissible: true %>

	 <button class="close" data-dismiss="alert" type="button">
	     <span aria-hidden="true">×</span><span class="sr-only">Close</span>
	   </button>

	 </div>
	 <% end %>
</div>


<% end %>

app/views/news/new.html.erb
<% content_for :admin do %>
<div class="container">
	<div class="row">

<div class="admin-panel ">
	<h1>Add a News Story</h1>

<%= render 'form' %>

<p class="bta"><i class="fa fa-arrow-left" aria-hidden="true"></i> <%= link_to 'Back to Admin', admin_path %>
</div>

</div>
</div>

<% end %>

app/views/news/show.html.erb
<%= content_for :head do %>
<script type='text/javascript' data-cfasync='false' src='//dsms0mj1bbhn4.cloudfront.net/assets/pub/shareaholic.js' data-shr-siteid='2a3a338d5a793821ef975b0f0e3b37ae' async='async'></script>

<% @title = @news.title %>

<% end %>

<%= content_for :full do %>

<div class="col-md-8 full">

	 	<% if current_user %>
	 	<div class="edit alert " >
	 <i> <%= link_to ' Edit ', edit_news_path(@news), class: "admin-edit fa fa-edit", dismissible: true %> </i>|<i> <%= link_to ' Delete', @news, method: :delete, data: { confirm: 'Are you sure?' }, class: "admin-edit fa fa-trash" %></i>
 
	 <button class="close" data-dismiss="alert" type="button">
	     <span aria-hidden="true">×</span><span class="sr-only">Close</span>
	   </button>
   
	 </div>
	<% end %>
	
  <h2>
  <%= @news.title %>
</h2>

<div class="date-share-row">
<div class="col-sm-4 date-col">
<h6 class="text-muted"><%= @news.published_at.to_time.strftime('%B %d %Y')%></h6> 
</div>
<div class="col-sm-8 share-col">
	<div class='shareaholic-canvas share-icons' data-app='share_buttons' data-app-id='25528828'></div>
</div>
</div>


 <% if @news.avatar.blank? %>
 
	
	
 <% else %>
<div class="news-img">
 <%= image_tag @news.avatar.url(:medium), class:"img-fluid news-img"%>
</div>
 <% end%>
	
<p class="news-intro">
 
  <%= @news.intro %>
</p>


<div class="pr-body"><%= simple_format(@news.body) %></div>

<p class="bta"><i class="fa fa-arrow-left" aria-hidden="true"></i> <%= link_to 'Back to News', news_index_path %>
	
</div>

<div class="rh col-md-4">
	<h4 class="also-news">Also in the News</h4>

	
	 	
	
	<% @ns.each do |ns| %>
	<% unless ns == @news %>
	<h4><%= link_to ns.title, ns %></h4>
	<h6 class="text-muted"><%= ns.published_at.to_time.strftime('%B %d %Y')%></h6>
	<% end %>
	<% end %>
	<p></p>
		<h6><i class="fa fa-arrow-left" aria-hidden="true"></i> <%= link_to 'All News', news_index_path %></h6>
</div>
<% end %>