config/routes.rb
Rails.application.routes.draw do
 
 
 resources :news
 resources :pressreleases
 

  resources :endorsements
  resources :users
    get '/signup' => 'users#new'
    post '/users' => 'users#create'
    get 'users', to: 'users#index'
    
    
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
    

 get 'contact/new'
 resources :contact, only: [:new, :create]
 get '/contact', to: 'contact#new'
 
 match '/send_mail', to: 'contact#send_mail', via: 'post'
 
 get 'admin/' => 'admin#index'
 
  get 'donate/' => 'donate#index'

  get 'support/' => 'support#index'
  
   get 'edit_organizations' => 'endorsements#edit_organizations'

  get 'endorsements' => 'endorsements#index'
  
 

  get 'faq/' => 'faq#index'

  get 'about/' => 'about#index'

  get 'welcome/index'

  root 'welcome#index'

end

app/models/contact.rb
class Contact 
  
  include ActiveModel::Model

  attr_accessor :firstname, :lastname, :email, :message, :type, :endorser, :mailingaddress, :city, :state, :zip, :phone, :language

  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :email, presence: true
 
end

app/models/endorsement.rb
class Endorsement < ActiveRecord::Base
 
 
 
default_scope  {order 'ranking ASC', 'lastname ASC', 'organization ASC'}
   
   validates :category, presence: true
end

app/models/news.rb
class News < ActiveRecord::Base
 extend FriendlyId
   friendly_id :title, use: :slugged
   
 has_attached_file :avatar, styles: { medium: "585x380#>", thumb: "120x80>" }, default_url: "/images/missing.png"


 validates_attachment :avatar,
   content_type: { content_type: ["image/jpg", "image/JPEG", "image/JPG", "image/jpeg", "image/gif", "image/png"] }
   
    default_scope  {order 'published_at DESC'}
    
end

app/models/pressrelease.rb
class Pressrelease < ActiveRecord::Base
 extend FriendlyId
   friendly_id :title, use: :slugged
   
  validates :title, presence: true
  validates :intro, presence: true
  validates :body, presence: true
  
   default_scope  {order 'publish_at DESC'}
   
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
   @title = "About Prop 58"
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
 
 before_filter :authorize 
 
  def index
   @title = "Admin Center"
  end
end

app/controllers/donate_controller.rb
class DonateController < ApplicationController
  def index
   @title = "Contribute to Prop 58"
  end
end

app/controllers/endorsements_controller.rb
class EndorsementsController < ApplicationController
  before_action :set_endorsement, only: [:show, :edit, :update, :destroy]

before_filter :authorize, except: [:index]


   
  def index
    @endorsement = Endorsement.all
    @title = "Endorsements for Prop 58"
  end
  
 

  
  def show
   
  end

  # GET /issues/new
  def new
    @endorsement = Endorsement.new
  end

  
  def edit
  end


  def create
    @endorsement = Endorsement.new(endorsement_params)

    respond_to do |format|
      if @endorsement.save
        format.html { redirect_to endorsements_url, notice: 'Endorsement was successfully created.' }
        format.json { render :show, status: :created, location: @endorsement }
      else
        format.html { render :new }
        format.json { render json: @endorsement.errors, status: :unprocessable_entity }
      end
    end
  end

   
   
  def update
    respond_to do |format|
      if @endorsement.update(endorsement_params)
        format.html { redirect_to endorsements_url, notice: 'Endorsement was successfully updated.' }
        format.json { render :show, status: :ok, location: @endorsement }
      else
        format.html { render :edit }
        format.json { render json: @endorsement.errors, status: :unprocessable_entity }
      end
    end
  end

 
  def destroy
    @endorsement.destroy
    respond_to do |format|
      format.html { redirect_to endorsements_url, notice: 'Endorsement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_endorsement
      @endorsement = Endorsement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def endorsement_params
      params.require(:endorsement).permit(:endorsement_id, :firstname, :lastname, :title, :organization, :ranking, :category)
    end
end

app/controllers/faq_controller.rb
class FaqController < ApplicationController

  def index
   @title = "Frequently Asked Questions"
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]
before_filter :authorize, except: [:index, :show]
  # GET /news
  # GET /news.json
  def index
    @news = News.all
    @title = "News"
  end

  # GET /news/1
  # GET /news/1.json
  def show
   @ns = News.all
  
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)
    
    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url, notice: 'News was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:title, :intro, :body, :published_at, :avatar)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :set_user, only: [:show, :edit, :update, :destroy]
before_filter :authorize


 def index
  @users = User.all
 end
 
 
  def new
  end

  def create
    user = User.new(user_params)
    if user.save
      
      redirect_to users_path, notice: 'User has been added!'
    else
      redirect_to '/signup'
    end
  end
  
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private
 # Use callbacks to share common setup or constraints between actions.
 def set_user
   @user = User.find(params[:id])
 end
 
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/donate_helper.rb
module DonateHelper
end

app/helpers/endorsements_helper.rb
module EndorsementsHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/pressreleases_helper.rb
module PressreleasesHelper
end

app/helpers/support_helper.rb
module SupportHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/endorsements/_form.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script>
$(document).ready(function(){
    $("#flip").click(function(){
        $("#panel").slideToggle("slow");
    });
});
</script>
<%= bootstrap_form_for(@endorsement) do |f| %>
  <% if @endorsement.errors.any? %>
    <div id="error_explanation" class="form-errors">
      <p><%= pluralize(@endorsement.errors.count, "error") %> prohibited this endorsement from being saved:</p>


    </div>
  <% end %>




 <fieldset class="form-group">

	 <div class="controls ">
		  <%= f.label :ranking %><span id="flip">What's this?</span>
			<div id="panel"><p>Ranking allows you to order elected officials according to their seniority, rather than alphabetically.

			<p>Spread out the ranks and you will be able to insert an in-between office later on if needed.

			<p>For example, 100, 200, 300 etc is better than 1,2,3...</p>
		</div>
	  <%= f.text_field :ranking, placeholder: "10, 50, 1000, etc... 0 is highest", hide_label: true%>
	 </div>

 <div class="controls ">
  <%= f.text_field :title, placeholder: "Governor, Councilmember, etc", label: "Title (for electeds)"%>
 </div>

  <div class="controls">
	  <%= f.text_field :firstname %>
  </div>

  <div class="controls">
	  <%= f.text_field :lastname %>
  </div>


  <div class="controls">
	  <%= f.text_field :organization, label: "Organization / District (or office to be displayed after name)"%>
  </div>

  <div class="controls">
	<%= f.select :category,  [["Organization", 1], ["Newspaper",5], [ "Elected Official",2], ["Educators and Community Leaders",3], ["School District",4] ],{ include_blank: true , label: "Please choose one:" }, { class: "selectpicker" } %>
  </div>

</fieldset>

  <div class="actions pull-right">
    <%= f.submit %>
  </div>
<% end %>

app/views/endorsements/edit.html.erb
<% content_for :admin do %>
<div class="container">
	<div class="row">

<div class="admin-panel ">
	<h1>Edit Endorser</h1>
	
	
<%= render 'form' %>



<p class="bta"><i class="fa fa-arrow-left" aria-hidden="true"></i> <%= link_to 'Back to Admin', admin_path %>
</div>

</div>
</div>
<% end %>

app/views/endorsements/edit_organizations.html.erb
<%= content_for :jumbotron do %>
<div class="endorsements-jumbotron">
    <!-- Intro Section -->
    <section id="intro" class="intro-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                   
					
                    
                </div>
            </div>
        </div>
    </section>
</div>
					
<% end %>														
<div class="sub-intro-section">
        <div class="container">
            <div class="row ">
								 <h2>Endorsements for LEARN</h2>
														
	<% if current_user %><div class="edit alert" >
	 <%= link_to ' Add a new endorsement', new_endorsement_path, class: "admin-edit fa fa-plus", dismissible: true %>

	 <button class="close" data-dismiss="alert" type="button">
	     <span aria-hidden="true">×</span><span class="sr-only">Close</span>
	   </button>

	 </div>
	 <% end %>
		
															
			 
			  <p>This initiative expands opportunities for all students and is supported by a bipartisan coalition of parents, educators and business leaders.</p>
									
						<h3>To add your name to the growing list of LEARN supporters, just <%= link_to 'fill out this form', contact_path %>.</h3>					
									
									

</p>

</div>
</div>
</div>
   
    <section class="a-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 col-lg-offset-1 endorsers">
                    <h2>Organizations</h2>
																				
<table class="table  " id="sortable">
  
 
    <% @endorsement.where(:category => '1').each do |endorsement| %>
      <tr data-item-id=<%= "#{endorsement.id}" %> class="item table-sortable">
        <td >
          <%= endorsement.organization %>
        
															<% if current_user %>
														<span class="edit-endorsement edit" >
								 <i> <%= link_to ' Edit ', edit_endorsement_path(endorsement), class: "admin-edit fa fa-edit", dismissible: true %> </i>|<i> <%= link_to ' Delete', endorsement, method: :delete, data: { confirm: 'Are you sure?' }, class: "admin-edit fa fa-trash" %></i>
 
 
   
								 </span>
         	<% end %>
        </td>
      </tr>
    <% end %>
 
</table>


														 
																																																

                </div>
            </div>
        </div>
    </section>
	

																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																					    <section class="b-section">
																																																																																																																																																																																																																																				        <div class="container">
																																																																																																																																																																																																																													            <div class="row">
																																																																																																																																																																																																																																																																																													                <div class="col-lg-10 col-lg-offset-1">
<div class="support-58">
																																																														<h1>Support our students by adding your name 
to the list of endorsers that are voting YES on 58</h1>
																																																				<p><%= link_to 'Support Prop 58', support_path, class: "btn btn-primary" %></p>																																																																																																																																																																																																																																																																																																							                </div>
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																													            </div>
																																																																																																																																																																																																																																																																																																																																																												        </div>
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																											    </section>
	
	
    

app/views/endorsements/new.html.erb
<% content_for :admin do %>
<div class="container">
	<div class="row">

<div class="admin-panel ">
	<h1>Add Endorser</h1>
	
	
<%= render 'form' %>


<p class="bta"><i class="fa fa-arrow-left" aria-hidden="true"></i> <%= link_to 'Back to Admin', admin_path %>
</div>

</div>
</div>
<% end %>

app/views/endorsements/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_endorsement_path(@endorsement) %> |
<%= link_to 'Back', endorsements_path %>